<?php /* coding: utf-8 */



require_once dirname(__file__).'/../../class/loader.php';

/**
 * Test class for devise.
 * Generated by PHPUnit on 2010-08-17 at 17:00:23.
 */
class deviseTest extends PHPUnit_Framework_TestCase{
	/**
	 * @var banque
	 */
	protected $object;


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(){
		global $gsb_xml;
		global $gsb_devises;
		//on prend le fichier de test et on remplace avec celui actuel
		copy('G:/zmws/_web.zmwsc/comptes/tests/fichiers/test_original.gsb','test.gsb');
		$gsb_xml=new xml('test.gsb');
		$this->object=$gsb_devises->get_by_id(1);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown(){
		@unlink('test.gsb');
	}
	public function testGet_id(){
		$this->assertEquals(1,$this->object->get_id());
	}
	public function testGet_nom(){
		$this->assertEquals('Euro',$this->object->get_nom());
	}

	/**
	 * Generated from @assert () == html_entity_decode("&#x20AC;","utf-8").
	 */
	public function testGet_code() {
		$this->assertEquals( html_entity_decode("&#x20AC;",ENT_COMPAT,"utf-8"), $this->object->get_code());
	}

	/**
	 * Generated from @assert () == 'EUR'.
	 */
	public function testGet_isoCode() {
		$this->assertEquals( 'EUR', $this->object->get_isocode());
	}

	public function testGet_Date_dernier_change() {
		global $gsb_devises;
		$this->assertEquals( util::datefr2time("01/01/2010"), $gsb_devises->get_by_id(2)->get_date_dernier_change() );
	}

	public function testGet_change() {
		global $gsb_devises;
		$this->assertEquals( 10, $gsb_devises->get_by_id(2)->get_change());
	}
	public function testGet_change_egal_a_1() {
		global $gsb_devises;
		$this->assertEquals( 1, $gsb_devises->get_by_id(1)->get_change());
	}

}
?>