<?php  /* coding: utf-8 */ 

require_once 'PHPUnit/Framework.php';

require_once 'G:\zmws\_web.zmwsc\comptes\class\loader.php';

/**
 * Test class for etat.
 * Generated by PHPUnit on 2010-08-17 at 17:00:23.
 */
class etatTest extends PHPUnit_Framework_TestCase{
	/**
	 * @var banque
	 */
	protected $object;


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(){
		global $gsb_xml;
		global $gsb_etats;
	//on prend le fichier de test et on remplace avec celui actuel
		copy('G:/zmws/_web.zmwsc/comptes/tests/fichiers/test_original.gsb','test.gsb');
		$gsb_xml=new xml('test.gsb');
		$this->object=$gsb_etats->get_by_id(1);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown(){
		@unlink('test.gsb');
	}
	public function testGet_id(){
		$this->assertEquals(1,$this->object->get_id(1));
	}
	public function testGet_nom(){
		$this->assertEquals('Revenus et depenses du mois precedent',$this->object->get_nom(1));
	}

}
?>