<?php
// $Id: rappsTest.php 33 2010-08-22 22:54:52Z pfrancois $
require_once 'PHPUnit/Framework.php';
require_once 'G:\zmws\_web.zmwsc\comptes\class\loader.php';
/**
 * Test class for rapps.
 * Generated by PHPUnit on 2010-08-17 at 21:08:16.
 */
class rappsTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var rapps
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()	{
		global $gsb_xml;
		global $gsb_rapps;
		//on prend le fichier de test et on remplace avec celui actuel
		copy('G:/zmws/_web.zmwsc/comptes/tests/fichiers/test_original.gsb','test.gsb');
		$gsb_xml=new xml('test.gsb');
		$gsb_xml->reload();
		$this->object = $gsb_rapps;
	}
	protected function tearDown(){
		@unlink('test.gsb');
	}
	/**
	 * test afin de voir si on recoit bien le rapprochement que l'on veut
	 */
	public function testGet_by_id()	{
		$r=$this->object->get_by_id(1);
		$this->assertType('rapp',$r);
		$this->assertEquals(1,$r->get_id());
	}
	/**
	 * test afin de voir si en lui donnant un id de rapporchement inexistant il renvoit bien une exception
	 * @expectedException exception_not_exist
	 */
	public function testGet_by_id_id_inexistant()	{
		$r=$this->object->get_by_id(235400);
	}

	/**
	 * test afin de voir si je peux recuperer le numero du rapporchement inexistant
	 */
	public function testGet_by_id_id_inexistant_recup_numero_rapporchements()	{
		try{
			$r=$this->object->get_by_id(235400);
		}catch (exception_not_exist $e) {
			$this->assertEquals(235400,$e->id);
		}
	}
	/**
	 * test afin de voir si en lui donnant une valeur incorrect (une chaine au lieur d'un chiffre) il renvoit bien une exception
	* @expectedException exception_parametre_invalide
	 */
	public function testGet_by_id_var_incorrect()	{
		$r=$this->object->get_by_id('toto');
	}

	public function testGet_next()	{
		$r=$this->object->get_next();
		$this->assertEquals(2,$r);
	}

	/**
	* verifie que l'implementation de count marche
	*/
	public function test_count(){
		$this->assertEquals(1,count($this->object));
	}
	/**
	* test que ca nous renvoit un iter comme on veut
	*/
	public function testiter_rapprochements(){
		$x=$this->object->iter();
		foreach ($x as $y){
			$this->assertType('rapp',$y);
		}
		$this->assertEquals(1,count($x));
	}

	public function test_new_rapp(){
		$n=$this->object->new_rapp();
		$this->assertEquals(date("c"),$n->get_nom());
		$this->assertEquals(2,$n->get_id());
	}
	public function test_new_rapp2(){
		$n=$this->object->new_rapp(7);
		$this->assertEquals(date("c"),$n->get_nom());
		$this->assertEquals(7,$n->get_id());
	}
	/**
	 * test afin de voir si en lui donnant une valeur incorrect (une chaine au lieur d'un chiffre) il renvoit bien une exception
	 * @expectedException exception_parametre_invalide
	 */
	public function test_new_rapp3(){
		$n=$this->object->new_rapp('toto');
	}
	/**
	 * test afin de voir si en lui donnant une valeur incorrect (une chaine au lieur d'un chiffre) il renvoit bien une exception
	* @expectedException exception_index
	 */
	public function test_new_rapp4(){
		$n=$this->object->new_rapp('1');
	}
}
