<?php
// $Id: rappTest.php 33 2010-08-22 22:54:52Z pfrancois $
require_once 'PHPUnit/Framework.php';

require_once 'G:\zmws\_web.zmwsc\comptes\class\loader.php';

/**
 * Test class for rapp.
 * Generated by PHPUnit on 2010-08-17 at 17:00:23.
 */
class rappTest extends PHPUnit_Framework_TestCase{
	/**
	 * @var banque
	 */
	protected $object;


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(){
		global $gsb_xml;
		global $gsb_rapps;
	//on prend le fichier de test et on remplace avec celui actuel
		copy('G:/zmws/_web.zmwsc/comptes/tests/fichiers/test_original.gsb','test.gsb');
		$gsb_xml=new xml('test.gsb');
		$this->object=$gsb_rapps->get_by_id(1);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown(){
		@unlink('test.gsb');
	}

	public function testGet_id(){
		$this->assertEquals(1,$this->object->get_id());
	}
	public function testGet_nom(){
		$this->assertEquals('CBO1',$this->object->get_nom());
	}


}

